// LNS addition of two log-domain terms X = log2(A*B), Y = log2(C*D):
//     s = max(X,Y) + F(|X-Y|)          F from lns_ftable (generated by model.py)
// zx/zy flag a zero term (log undefined); zero terms are dropped, and if both
// terms are zero the sum itself is zero (s_zero).
// All values are in 1/2^K-log2 units (integers).
`default_nettype none
module lns_add #(
    parameter LW = 8          // width of X,Y  (max L(A)+L(B) = DMAX)
) (
    input  wire [LW-1:0]  X,
    input  wire [LW-1:0]  Y,
    input  wire           zx,      // term X (A*B) is zero
    input  wire           zy,      // term Y (C*D) is zero
    output reg  [LW:0]    s,       // max + F(d)  (max value 20)
    output reg            s_zero   // whole sum is zero
);
    wire [LW-1:0] d  = (X > Y) ? (X - Y) : (Y - X);   // |X-Y|
    wire [LW-1:0] mx = (X > Y) ? X : Y;               // max(X,Y)
    wire [3:0]    Fd;
    lns_ftable FT (.d(d[7:0]), .f(Fd));   // F-ROM: byte-wide index, nibble value (see model.py)

    always @* begin
        if (zx && zy) begin s_zero = 1'b1; s = {(LW+1){1'b0}}; end
        else if (zx)  begin s_zero = 1'b0; s = {1'b0, Y};      end
        else if (zy)  begin s_zero = 1'b0; s = {1'b0, X};      end
        else          begin s_zero = 1'b0; s = mx + Fd;        end
    end
endmodule
`default_nettype wire
