/* Generated by Yosys 0.55 (git sha1 60f126cd0, ccache clang 18.1.3 -O3 -flto -flto) */

module lns_ftable(d, f);
  wire _0_;
  wire _1_;
  wire _2_;
  input [7:0] d;
  wire [7:0] d;
  output [3:0] f;
  wire [3:0] f;
  sky130_fd_sc_hd__or4_1 _3_ (
    .A(d[7]),
    .B(d[4]),
    .C(d[5]),
    .D(d[6]),
    .X(_0_)
  );
  sky130_fd_sc_hd__nor2_1 _4_ (
    .A(d[3]),
    .B(d[1]),
    .Y(_1_)
  );
  sky130_fd_sc_hd__a211oi_1 _5_ (
    .A1(d[2]),
    .A2(d[1]),
    .B1(_0_),
    .C1(_1_),
    .Y(f[0])
  );
  sky130_fd_sc_hd__nor2_1 _6_ (
    .A(d[2]),
    .B(d[1]),
    .Y(_2_)
  );
  sky130_fd_sc_hd__nor3_1 _7_ (
    .A(d[3]),
    .B(_0_),
    .C(_2_),
    .Y(f[1])
  );
  sky130_fd_sc_hd__nor4_1 _8_ (
    .A(d[3]),
    .B(d[2]),
    .C(d[1]),
    .D(_0_),
    .Y(f[2])
  );
  assign f[3] = 1'h0;
endmodule
